project:
  type: website

website:
  title: "Saalfeld lab blog"
  image: logo.png
  favicon: favicon.ico
  navbar:
    logo: logo.png
    right:
      - about.qmd
      - icon: github
        href: https://github.com/saalfeldlab
      - icon: mastodon
        href: https://mastodon.social/@herrsaalfeld
format:
  html:
    theme: cosmo 
    css: styles.css



